#!/usr/bin/env bash
#installs and configures the loadbalancer haproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get -y install haproxy=2.9.\*
sudo chown -R $USER:$USER /etc/haproxy/
sudo apt-get -y update
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo  "
frontend gemi
	bind *:80
	mode http
	default_backend oreo
backend oreo
	balance roundrobin
	server 340120-web-01 100.25.194.118:80 check
	server 340120-web-02 54.196.26.252:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
