#!/usr/bin/env bash
#configures an nginx server to listen on port 80

#removing the default nginx configuration file
rm /etc/nginx/sites-enabled/default

#configure nginx to listen on port 80 on all ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
sudo service nginx restart
